version: '3.0'
services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    environment:
      - REDIS_HOST=redis
    env_file:
      - secrects.env
  backend:
    image: cooler:latest
    build:
      context: backend
    ports: 
      - "7643:8080"
  frontend:
    image: nginx:1.23.3
    ports: 
      - "7644:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  redis_data:
