version: '3.0'
services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
  backend:
    image: cooler:latest
    build:
      context: backend
    ports: 
      - "7643:8080"
    environment:
      - REDIS_HOST=redis
    env_file:
      - secrets.env
  frontend:
    image: nginx:1.23.3
    ports: 
      - "7644:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
  cron:
    image: cooler-cron:latest
    build:
      context: backend/crontab
    env_file:
      - secrets.env

volumes:
  redis_data:
